manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: inorichi
      url-base: https://github.com/inorichi
    # - name: sadekbaroudi
    #   url-base: https://github.com/sadekbaroudi
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
    #   path: drivers/zmk-pmw3610-driver
    # - name: zmk-pmw3610-driver
    #   remote: sadekbaroudi
    #   revision: main
    # - name: zmk-pmw3610-driver
    #   remote: badjeff
    #   revision: main
  self:
    path: config